# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: myfirstmicroservice
services:
  postgresql:
    image: postgres:17.4
    # volumes:
    #   - ~/volumes/jhipster/myFirstMicroService/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=myFirstMicroService
      - POSTGRES_PASSWORD=test_password
    volumes:
      - ./pgdata:/var/lib/postgresql/data  # Change to bind mount data directory
      - ./custom_pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: >
      bash -c "
        if [ ! -f /var/lib/postgresql/data/PG_VERSION ]; then
          echo 'Initializing database directory...';
        fi
        cp /etc/postgresql/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf;
        exec docker-entrypoint.sh postgres"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  pgadmin_data:
